// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHFe6p2ILs6ToLsfAVX5QPL7XFzBZRusE',
    appId: '1:253401132914:web:8689b228d41419d8b077eb',
    messagingSenderId: '253401132914',
    projectId: 'aplikasi-inventori-android',
    authDomain: 'aplikasi-inventori-android.firebaseapp.com',
    storageBucket: 'aplikasi-inventori-android.appspot.com',
    measurementId: 'G-RGM51VCC0M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr4TV3Azxye26jlx6h67NWmcAzaU__s4U',
    appId: '1:253401132914:android:0fcb978aa74f881bb077eb',
    messagingSenderId: '253401132914',
    projectId: 'aplikasi-inventori-android',
    storageBucket: 'aplikasi-inventori-android.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6Mv2Bhb4ZtJWTVqVbbhes6iqVDQxRUO8',
    appId: '1:253401132914:ios:8a0177055be4837cb077eb',
    messagingSenderId: '253401132914',
    projectId: 'aplikasi-inventori-android',
    storageBucket: 'aplikasi-inventori-android.appspot.com',
    iosClientId: '253401132914-8u8fsh7ubfmkstthllvadcmjmsgvdika.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectAmbw',
  );
}
